通过UDP获取服务器地址
uuiid/Doodle pull request #3
Opened 2023-09-05 05:10 UTC by hangshow2011

1.设置广播地址
2.发送广播消息
3.创建监听socket
3.监听接收消息
4.处理接收到消息
5.写入远程服务器的IP地址
6.创建UDP接收线程，提交渲染成功

2023-09-05 05:12 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/DoodleEditor.Build.cs
> +				"Sockets",
使用私有模块连接

2023-09-05 05:13 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  FString Remote_Server_Ip = ("127.0.0.1");
大括号初始化, 不要使用赋值初始化, 最好初始化在构造函数中

2023-09-05 05:14 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +
最好去除注释

2023-09-05 05:15 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  FSocket* socket2 = nullptr;
类属性名称开头大小

2023-09-05 05:16 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    FString rec_data = ((const char*)data);
这里直接转换是否可行?

2023-09-05 05:17 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        udp_rec = new FUdpSocketReceiver(socket2, FTimespan::FromSeconds(1000), TEXT("rec_thread"));
使用智能指针, 不要new对象

2023-09-05 05:18 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (socket2 == nullptr)
启动函数位置不对

2023-09-05 05:22 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        socket2 = FUdpSocketBuilder(TEXT("udp2")).AsNonBlocking().WithBroadcast().AsReusable().Build();
使用智能指针

2023-09-05 05:23 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        udp_rec = new FUdpSocketReceiver(socket2, FTimespan::FromSeconds(1000), TEXT("rec_thread"));
好的，我改下

2023-09-05 05:23 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (socket2 == nullptr)
?

2023-09-05 05:25 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (socket2 == nullptr)
UDoodleMovieRemoteExecutor::FindRemoteClient() 在这个方法之前获取服务器ip, 并在完成ip获取后调用此方法, 失败后给予用户提示

2023-09-05 05:29 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        bytes.Append((const uint8*)Converter.Get(), Converter.Length());
繁琐的转换, 使用宏 `UTF8_TO_TCHAR` 是否可行?

2023-09-05 05:33 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    TSharedPtr<FArrayReader> ar = MakeShareable(arrayRender.Get());
不需要创建动态指针

2023-09-05 05:34 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if(rec_data.Equals("hello world! doodle server"))
使用 `TEXT` 宏包裹

2023-09-05 05:35 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        }
使用智能指针时去除此处部分

2023-09-05 05:35 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        socket2 = nullptr;
使用智能指针时去除此处部分

2023-09-05 05:35 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        ISocketSubsystem::Get(PLATFORM_SOCKETSUBSYSTEM)->DestroySocket(socket2);
使用智能指针时去除此处部分

2023-09-05 05:38 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    GEditor->GetTimerManager().Get().ClearTimer(TimerHandle);
未找到的情况需要用户提示

2023-09-05 05:39 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        GEditor->GetTimerManager().Get().SetTimer(TimerHandle, this, &UDoodleMovieRemoteExecutor::UDPOnTimeout, 3, true);
在不重试的情况下超时只有一次

2023-09-05 05:40 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    GEditor->GetTimerManager().Get().ClearTimer(TimerHandle);
不需要清除计时器,  有manager清除

2023-09-05 05:54 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +#include <Common/UdpSocketReceiver.h>
转移到cpp中

2023-09-05 05:55 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  FUdpSocketReceiver* udp_rec = nullptr;
提前声明

2023-09-05 05:55 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  FSocket* socket2 = nullptr;
提前声明

2023-09-06 07:46 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  TSharedPtr<FUdpSocketReceiver> udp_rec = nullptr;
代码重复

2023-09-06 07:46 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/DoodleEditor.Build.cs
> +				"Networking",
去掉应该可以

2023-09-06 07:51 UTC, uuiid requested changes

2023-09-06 07:51 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +                    UE_LOG(LogMovieRenderPipeline, Error, TEXT("Process: %s"), TEXT("析构"));
取消日志记录

2023-09-06 07:51 UTC, uuiid requested changes

2023-09-06 07:51 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  void UDPReceiver(const FArrayReaderPtr& ArrayRender, const FIPv4Endpoint& Endpoint);
重复

2023-09-06 07:58 UTC, uuiid requested changes

2023-09-06 07:58 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +  void UDPReceiver(const FArrayReaderPtr& ArrayRender, const FIPv4Endpoint& Endpoint);
重复

2023-09-06 08:08 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.h
> +typedef TSharedPtr<FArrayReader, ESPMode::ThreadSafe> FArrayReaderPtr;
添加 提前声明后不需要头文件 `<Common/UdpSocketReceiver.h>`

2023-09-06 08:10 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
缺失非空分支,  这里可以不需要测试指针是否为空

2023-09-06 08:11 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
防止连续点击

2023-09-06 08:12 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
非空就是还在进行中，等待超时

2023-09-06 08:14 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
连续点击我记得会生成两个实例,  测试非空应该没有用吧

2023-09-06 08:16 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
这样的吗？我测了一下，连点，好像会卡，但我也不知道是什么问题，不知道是否其他代码影响到

2023-09-06 08:18 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
连续点击时, 打印this指针可以看出时不同的实例,  在卡顿可能时没有使用后台线程复制文件或者网络原因吧

2023-09-06 08:21 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket == nullptr)
要不判断指针是否为空这个还是留着吧，不影响的，u3d插件是不会开多实例的，以前习惯这样写了

2023-09-06 08:36 UTC, uuiid requested changes

2023-09-06 08:36 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (rec_data.Equals(TEXT("hello world! doodle server")))
需要不相等的用户提示

2023-09-06 08:43 UTC, uuiid requested changes

2023-09-06 08:43 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    FString rec_data = FString::FromBlob(arrayRender->GetData(), arrayRender->Num());
使用这个吧 `UTF8_TO_TCHAR((char*)RecvMessageData->GetData())`

2023-09-06 08:44 UTC, uuiid requested changes

2023-09-06 08:44 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        FindRemoteClient();
欠缺取消计时器操作

2023-09-06 08:59 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (rec_data.Equals(TEXT("hello world! doodle server")))
不相等就是自己给自己发了，不处理

2023-09-06 09:01 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (rec_data.Equals(TEXT("hello world! doodle server")))
不管是先监听后发送，还是先发送后监听都会，收到自己的消息，之前测了一下

2023-09-06 09:21 UTC, uuiid requested changes

2023-09-06 09:21 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +    if (udp_socket != nullptr)
修正 `if (InOwningNotification) {}`

2023-09-06 09:21 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/Doodle/MovieRemoteExecutor.cpp
> +        udp_socket = nullptr;
使用 ` InOwningNotification.Reset();`

2023-09-07 02:54 UTC, uuiid approved these changes

2023-09-07 02:55 UTC, merged