[变体管理器] 兼容选择材质实例，变体管理器，显示人物预览
uuiid/Doodle pull request #5
Opened 2023-10-17 02:55 UTC by hangshow2011

2023-10-17 03:19 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +    return SNew(SDockTab).TabRole(ETabRole::NomadTab)[SNew(DoodleVariantCompoundWidget)];  // 杩欓噷鍒涘缓鎴戜滑鑷繁鐨勭晫闈
编码错误

2023-10-17 03:24 UTC, uuiid requested changes

2023-10-17 03:24 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                }
不要这么判断,  直接转换父类

2023-10-17 03:24 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                        .AutoHeight()
去掉

2023-10-17 03:24 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                        ]
使用填充

2023-10-17 03:25 UTC, uuiid requested changes

2023-10-17 03:25 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorToolkit.cpp
> +    In_TabManager->UnregisterAllTabSpawners();
不要在初始化的时候使用卸载所有

2023-10-17 03:29 UTC, uuiid requested changes

2023-10-17 03:29 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorToolkit.cpp
> +       FString NowVaraint = VariantEditorWidget->NowVaraint;
格式对齐

2023-10-17 06:44 UTC, uuiid requested changes

2023-10-17 06:44 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +        Info.FadeInDuration = 2.0f;  // 娣″叆娣″嚭鏃堕棿
错误的编码

2023-10-17 06:44 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                        ]
直接在上一个槽中填充

2023-10-17 06:44 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                        ]
或者槽中不要有小部件

2023-10-17 06:44 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Public/DoodleVariantCompoundWidget.h
>  	void OnVariantDelete();
所有类的,私有和公开方法做一下区分,

2023-10-17 08:33 UTC, uuiid requested changes
- 调整界面比例
- 添加聚焦
- 添加独显

2023-10-20 07:26 UTC, uuiid requested changes

2023-10-20 07:26 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorViewport.cpp
> +    const FSkeletalMeshRenderData& SkelMeshRenderData = MeshObject->GetSkeletalMeshRenderData();
这里缺少头文件的引用,  大概是 `FSkeletalMeshLODRenderData`和 `FSkelMeshRenderSection` 两个类的

2023-10-20 07:26 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +                            UE_LOG(LogTemp, Warning, TEXT("OnCheckStateChanged Hello World"));
去除不需要的日志

2023-10-20 07:26 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorViewport.cpp
> +    ViewportClient->FocusViewportOnBox(Box, true);
直接获取box, 应该不需要转换吧

2023-10-20 07:26 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorViewport.cpp
> +    }
这个代码在什么时候执行,  感觉永远不会执行

2023-10-20 07:26 UTC, uuiid commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantCompoundWidget.cpp
> +
多余的空格

2023-10-20 07:44 UTC, hangshow2011 commented on script/uePlug/Doodle/Source/DoodleEditor/Private/DoodleVariantEditorViewport.cpp
> +    ViewportClient->FocusViewportOnBox(Box, true);
大小是不同的

2023-10-20 08:58 UTC, merged